from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.scm import Git
from conan.tools.files import copy
import os
import shutil

class engine3dRecipe(ConanFile):
    name = "engine3d"
    version = "1.0"
    package_type = "library"
    license = "Apache-2.0"
    homepage = "https://github.com/engine3d-dev/engine3d"
    description = "Multipurpose 3D engine"
    topics = ("Engine", "Graphics", "Animations", "Simulations")
    
    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Specifying our build_type is only Debug and Release
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/CMakeLists.txt", "Editor/CMakeLists.txt", "src/*", "engine3d/*", "Editor/*"

    def build_requirements(self):
        self.tool_requires("make/4.4.1")
        self.tool_requires("cmake/3.27.1")
        self.tool_requires("engine3d-cmake-utils/2.0")

    def requirements(self):
        self.requires("glfw/3.4", transitive_headers=True)
        self.requires("fmt/10.2.1", transitive_headers=True)
        self.requires("spdlog/1.14.1", transitive_headers=True)
        self.requires("glm/1.0.1", transitive_headers=True)
        self.requires("yaml-cpp/0.8.0", transitive_headers=True)
        self.requires("box2d/2.4.1", transitive_headers=True)
        self.requires("opengl/system", transitive_headers=True)
        self.requires("imguidocking/2.0")

        # Vulkan-related headers and includes packages
        self.requires("vulkan-headers/1.3.290.0", transitive_headers=True)
        self.requires("flecs/4.0.0")
        self.requires("tinyobjloader/2.0.0-rc10")
        self.requires("joltphysics/1.0")

        self.requires("boost-ext-ut/2.1.0")

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if not self.settings.get_safe("build_type"):
            self.settings.build_type = "Debug"
        
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        # Cleanly removing engine3d_unit_test.dir
        # For some reason boost-ext/ut profiles and says that *.test.cpp.gcda is corrupted
        # This is to cleanly remove specifically the directory generated by cmake to cleanly run the tests
        # CMakeFiles/engine3d_unit_test.dir/tests/main.test.cpp.obj
        # We want to delete only files that are changed with *.test.cpp
        # Then we want to delete all of the same files with those names, but end with *.test.cpp.obj
        unit_test_dir = os.path.join(self.build_folder, "CMakeFiles\engine3d_unit_test.dir")
        print(f"unit test dir === {unit_test_dir}")

        if os.path.exists(unit_test_dir):
            print("Cleaning up unit_test directory cache")
            shutil.rmtree(unit_test_dir)

        cmake = CMake(self)
        # cmake.verbose = True
        cmake.configure()
        cmake.build()


    def package(self):
        copy(self, "LICENSE", src=self.source_folder, dst=os.path.join(self.package_folder, "licenses"))
        copy(self, pattern="*.h", src=os.path.join(self.source_folder, "engine3d"), dst=os.path.join(self.package_folder, "engine3d"))
        copy(self, pattern="*.a", src=self.build_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, pattern="*.so", src=self.build_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, pattern="*.lib", src=self.build_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        copy(self, pattern="*.dll", src=self.build_folder, dst=os.path.join(self.package_folder, "bin"), keep_path=False)
        copy(self, pattern="*.dylib", src=self.build_folder, dst=os.path.join(self.package_folder, "lib"), keep_path=False)
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.set_property("cmake_target_name", "engine3d::engine3d")
        self.cpp_info.libs = ["engine3d"]
        self.cpp_info.includedirs = ['./', './engine3d']  # Ordered list of include paths

    

    

