name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Install CMake 3.20
    - name: Install CMake 3.20
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.20.1
      id: review

    # Uploads an artefact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.14.0
      id: upload-review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
