name: 🚀 Deploy Version

on:
  workflow_dispatch:

jobs:
  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    uses: engine3d-dev/ci/.github/workflows/deploy.yml@1.x.y
    with:
      compiler: gcc
      version: ${{ github.ref_name }}
      arch: x86_64
      compiler_version: 12.3
      compiler_package: ""
      os: Linux
    secrets: inherit