name: Windows Build Tests

on: [push, pull_request]

jobs:
    windows-build:
        name: "Windows-Build"
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
        
            - name: Setting up C++ on Windows
              shell: powershell
              run: winget install Microsoft.VisualStudio.2022.BuildTools --override "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended -p --installWhileDownloading"
            
            - name: Installing Choco
              shell: powershell
              run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

            - name: Install tooling with Choco
              shell: powershell
              run: choco install git python llvm make cmake mingw
            
            - name: Pip installing conan
              shell: powershell
              run: pip install conan

            - name: Installing vulkan
              shell: powershell
              run: winget install --id=KhronosGroup.VulkanSDK -e
            
            - name: Setting up conan profiles
              shell: powershell
              run: conan config install -sf profiles/x86_64/Windows/ -tf profiles https://github.com/engine3d-dev/conan-config.git
            
            - name: Setting up packages
              shell: powershell
              run: conan remote add engine3d-conan https://libhal.jfrog.io/artifactory/api/conan/engine3d-conan
            
            - name: Running Test Cases
              shell: powershell
              run: conan build . -b missing
            
            